package py.gov.stp.mh.update_presupuesto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * @author		DGTIC-STP
 * @email		dgtic@stp.gov.py 
 *
 **/

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-09-24T12:38:32.630-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "UpdatesPresupuestoService", 
                  wsdlLocation = "localhost",
                  targetNamespace = "localhost") 
public class UpdatesPresupuestoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("localhost", "UpdatesPresupuestoService");
    public final static QName UpdatesPresupuestoPort = new QName("localhost", "UpdatesPresupuestoPort");
    static {
        URL url = null;
        try {
            url = new URL("localhost");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UpdatesPresupuestoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "localhost");
        }
        WSDL_LOCATION = url;
    }

    public UpdatesPresupuestoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UpdatesPresupuestoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdatesPresupuestoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdatesPresupuestoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdatesPresupuestoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UpdatesPresupuestoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UpdatesPresupuesto
     */
    @WebEndpoint(name = "UpdatesPresupuestoPort")
    public UpdatesPresupuesto getUpdatesPresupuestoPort() {
        return super.getPort(UpdatesPresupuestoPort, UpdatesPresupuesto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdatesPresupuesto
     */
    @WebEndpoint(name = "UpdatesPresupuestoPort")
    public UpdatesPresupuesto getUpdatesPresupuestoPort(WebServiceFeature... features) {
        return super.getPort(UpdatesPresupuestoPort, UpdatesPresupuesto.class, features);
    }

}
