package py.gov.stp.mh.consultas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
@author		DGTIC-STP
@email      dgtic@stp.gov.py
*/

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-07-25T08:27:00.442-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "localhost", name = "StpService")
@XmlSeeAlso({ObjectFactory.class})
public interface StpService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerProductosFisicos", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerProductosFisicos")
    @WebMethod
    @ResponseWrapper(localName = "obtenerProductosFisicosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerProductosFisicosResponse")
    public java.util.List<py.gov.stp.mh.consultas.ProductoFisico> obtenerProductosFisicos(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Integer anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Integer nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Integer entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Integer tipo,
        @WebParam(name = "programa", targetNamespace = "")
        java.lang.Integer programa,
        @WebParam(name = "subprograma", targetNamespace = "")
        java.lang.Integer subprograma,
        @WebParam(name = "proyecto", targetNamespace = "")
        java.lang.Integer proyecto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerPresupuestoDeGastos", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerPresupuestoDeGastos")
    @WebMethod
    @ResponseWrapper(localName = "obtenerPresupuestoDeGastosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerPresupuestoDeGastosResponse")
    public java.util.List<py.gov.stp.mh.consultas.PresupGastos> obtenerPresupuestoDeGastos(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Integer anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Integer nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Integer entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Integer tipo,
        @WebParam(name = "programa", targetNamespace = "")
        java.lang.Integer programa,
        @WebParam(name = "subprograma", targetNamespace = "")
        java.lang.Integer subprograma,
        @WebParam(name = "proyecto", targetNamespace = "")
        java.lang.Integer proyecto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDetalleFinancieroPorProducto", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerDetalleFinancieroPorProducto")
    @WebMethod
    @ResponseWrapper(localName = "obtenerDetalleFinancieroPorProductoResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.consultas.ObtenerDetalleFinancieroPorProductoResponse")
    public java.util.List<py.gov.stp.mh.consultas.ProductoFinanciero> obtenerDetalleFinancieroPorProducto(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Integer anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Integer nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Integer entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Integer tipo,
        @WebParam(name = "programa", targetNamespace = "")
        java.lang.Integer programa,
        @WebParam(name = "subprograma", targetNamespace = "")
        java.lang.Integer subprograma,
        @WebParam(name = "proyecto", targetNamespace = "")
        java.lang.Integer proyecto,
        @WebParam(name = "producto", targetNamespace = "")
        java.lang.Integer producto
    );
}
