package py.gov.stp.mh.clasificadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
@author		DGTIC-STP
@email      dgtic@stp.gov.py
*/

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-07-25T08:26:53.382-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "localhost", name = "Clasificadores")
@XmlSeeAlso({ObjectFactory.class})
public interface Clasificadores {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "todosLosProyectosPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProyectosPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "todosLosProyectosPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProyectosPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Proyecto> todosLosProyectosPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "entidades", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Entidades")
    @WebMethod
    @ResponseWrapper(localName = "entidadesResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.EntidadesResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Entidad> entidades(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "organismosFinanciadores", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.OrganismosFinanciadores")
    @WebMethod
    @ResponseWrapper(localName = "organismosFinanciadoresResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.OrganismosFinanciadoresResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.OrganismoFinanciador> organismosFinanciadores(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "catalogoDNCP", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.CatalogoDNCP")
    @WebMethod
    @ResponseWrapper(localName = "catalogoDNCPResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.CatalogoDNCPResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.PrecioDNCP> catalogoDNCP(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "planes", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Planes")
    @WebMethod
    @ResponseWrapper(localName = "planesResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.PlanesResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Plan> planes();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pilares", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Pilares")
    @WebMethod
    @ResponseWrapper(localName = "pilaresResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.PilaresResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Pilar> pilares();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unidadesJerarquicas", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesJerarquicas")
    @WebMethod
    @ResponseWrapper(localName = "unidadesJerarquicasResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesJerarquicasResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.UnidadJerarquica> unidadesJerarquicas(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "todosLosProgramasPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProgramasPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "todosLosProgramasPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProgramasPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Programa> todosLosProgramasPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "todosLosProductosPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProductosPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "todosLosProductosPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosProductosPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Producto> todosLosProductosPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "version", targetNamespace = "")
        java.lang.Short version
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fuentesDeFinanciamiento", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.FuentesDeFinanciamiento")
    @WebMethod
    @ResponseWrapper(localName = "fuentesDeFinanciamientoResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.FuentesDeFinanciamientoResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.FuenteFinanciamiento> fuentesDeFinanciamiento(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerVersionesPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ObtenerVersionesPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "obtenerVersionesPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ObtenerVersionesPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Version> obtenerVersionesPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "objetosDeGatos", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ObjetosDeGatos")
    @WebMethod
    @ResponseWrapper(localName = "objetosDeGatosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ObjetosDeGatosResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.ObjetoGasto> objetosDeGatos(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "proyectosSNIPAutorizados", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProyectosSNIPAutorizados")
    @WebMethod
    @ResponseWrapper(localName = "proyectosSNIPAutorizadosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProyectosSNIPAutorizadosResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.ProyectoSNIPAutorizado> proyectosSNIPAutorizados(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ejesPorPlan", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.EjesPorPlan")
    @WebMethod
    @ResponseWrapper(localName = "ejesPorPlanResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.EjesPorPlanResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.PlanEje> ejesPorPlan();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "todosLosSubprogramasPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosSubprogramasPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "todosLosSubprogramasPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodosLosSubprogramasPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Subprograma> todosLosSubprogramasPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ingresosPorOrigen", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.IngresosPorOrigen")
    @WebMethod
    @ResponseWrapper(localName = "ingresosPorOrigenResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.IngresosPorOrigenResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.IngresoOrigen> ingresosPorOrigen(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ingresosPorDetalle", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.IngresosPorDetalle")
    @WebMethod
    @ResponseWrapper(localName = "ingresosPorDetalleResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.IngresosPorDetalleResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.IngresoDetalle> ingresosPorDetalle(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "proyectos", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Proyectos")
    @WebMethod
    @ResponseWrapper(localName = "proyectosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProyectosResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Proyecto> proyectos(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Short tipo,
        @WebParam(name = "programa", targetNamespace = "")
        java.lang.Short programa,
        @WebParam(name = "subprograma", targetNamespace = "")
        java.lang.Short subprograma
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unidadesResponsables", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesResponsables")
    @WebMethod
    @ResponseWrapper(localName = "unidadesResponsablesResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesResponsablesResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.UnidadResponsable> unidadesResponsables(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "tiposDeProgramas", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TiposDeProgramas")
    @WebMethod
    @ResponseWrapper(localName = "tiposDeProgramasResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TiposDeProgramasResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.TipoPrograma> tiposDeProgramas(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "catalogoProductosMetas", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.CatalogoProductosMetas")
    @WebMethod
    @ResponseWrapper(localName = "catalogoProductosMetasResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.CatalogoProductosMetasResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.CatalogoProductoMeta> catalogoProductosMetas(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "subprogramas", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Subprogramas")
    @WebMethod
    @ResponseWrapper(localName = "subprogramasResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.SubprogramasResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Subprograma> subprogramas(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Short tipo,
        @WebParam(name = "programa", targetNamespace = "")
        java.lang.Short programa
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "niveles", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Niveles")
    @WebMethod
    @ResponseWrapper(localName = "nivelesResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.NivelesResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Nivel> niveles(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "todasLasEntidadesPorAnio", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodasLasEntidadesPorAnio")
    @WebMethod
    @ResponseWrapper(localName = "todasLasEntidadesPorAnioResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.TodasLasEntidadesPorAnioResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Entidad> todasLasEntidadesPorAnio(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "programas", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Programas")
    @WebMethod
    @ResponseWrapper(localName = "programasResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProgramasResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Programa> programas(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.Short tipo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "departamentos", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Departamentos")
    @WebMethod
    @ResponseWrapper(localName = "departamentosResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.DepartamentosResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Departamento> departamentos(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "pais", targetNamespace = "")
        java.lang.Short pais
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "funcionales", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.Funcionales")
    @WebMethod
    @ResponseWrapper(localName = "funcionalesResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.FuncionalesResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.Funcional> funcionales(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "proyectosSNIP", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProyectosSNIP")
    @WebMethod
    @ResponseWrapper(localName = "proyectosSNIPResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.ProyectosSNIPResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.ProyectoSNIP> proyectosSNIP();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unidadesDeMedida", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesDeMedida")
    @WebMethod
    @ResponseWrapper(localName = "unidadesDeMedidaResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.clasificadores.UnidadesDeMedidaResponse")
    public java.util.List<py.gov.stp.mh.clasificadores.UnidadMedida> unidadesDeMedida();
}
