package py.gov.stp.mh.inserts_presupuesto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
@author		DGTIC-STP
@email      dgtic@stp.gov.py
*/

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-07-25T08:27:05.018-04:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "localhost", name = "InsertsPresupuesto")
@XmlSeeAlso({ObjectFactory.class})
public interface InsertsPresupuesto {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarProyecto", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyecto")
    @WebMethod
    @ResponseWrapper(localName = "insertarProyectoResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyectoResponse")
    public java.lang.Short insertarProyecto(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "codigoSubprograma", targetNamespace = "")
        java.lang.Short codigoSubprograma,
        @WebParam(name = "codigoProyecto", targetNamespace = "")
        java.lang.Short codigoProyecto,
        @WebParam(name = "unrCodigo", targetNamespace = "")
        java.lang.Short unrCodigo,
        @WebParam(name = "nombreProyecto", targetNamespace = "")
        java.lang.String nombreProyecto,
        @WebParam(name = "abrevProyecto", targetNamespace = "")
        java.lang.String abrevProyecto,
        @WebParam(name = "descripcion", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(name = "codigoDepto", targetNamespace = "")
        java.lang.Short codigoDepto,
        @WebParam(name = "resultadoEsperado", targetNamespace = "")
        java.lang.String resultadoEsperado,
        @WebParam(name = "diagnostico", targetNamespace = "")
        java.lang.String diagnostico,
        @WebParam(name = "codigoFuncional", targetNamespace = "")
        java.lang.Short codigoFuncional
    ) throws WsException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarSubprograma", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarSubprograma")
    @WebMethod
    @ResponseWrapper(localName = "insertarSubprogramaResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarSubprogramaResponse")
    public java.lang.Short insertarSubprograma(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "codigoSubprograma", targetNamespace = "")
        java.lang.Short codigoSubprograma,
        @WebParam(name = "nombreSubprograma", targetNamespace = "")
        java.lang.String nombreSubprograma,
        @WebParam(name = "abrevSubprograma", targetNamespace = "")
        java.lang.String abrevSubprograma,
        @WebParam(name = "descripcion", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(name = "codigoDepto", targetNamespace = "")
        java.lang.Short codigoDepto,
        @WebParam(name = "objetivo", targetNamespace = "")
        java.lang.String objetivo
    ) throws WsException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarProyectoPlanEstrategico", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyectoPlanEstrategico")
    @WebMethod
    @ResponseWrapper(localName = "insertarProyectoPlanEstrategicoResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyectoPlanEstrategicoResponse")
    public java.lang.Short insertarProyectoPlanEstrategico(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "codigoSubprograma", targetNamespace = "")
        java.lang.Short codigoSubprograma,
        @WebParam(name = "codigoProyecto", targetNamespace = "")
        java.lang.Short codigoProyecto,
        @WebParam(name = "codigoPlan", targetNamespace = "")
        java.lang.Short codigoPlan,
        @WebParam(name = "codigoPilar", targetNamespace = "")
        java.lang.Short codigoPilar
    ) throws WsException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarProducto", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProducto")
    @WebMethod
    @ResponseWrapper(localName = "insertarProductoResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProductoResponse")
    public java.lang.Short insertarProducto(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "codigoSubprograma", targetNamespace = "")
        java.lang.Short codigoSubprograma,
        @WebParam(name = "codigoProyecto", targetNamespace = "")
        java.lang.Short codigoProyecto,
        @WebParam(name = "codigoProducto", targetNamespace = "")
        java.lang.Short codigoProducto,
        @WebParam(name = "metaEnero", targetNamespace = "")
        java.lang.Double metaEnero,
        @WebParam(name = "metaFebrero", targetNamespace = "")
        java.lang.Double metaFebrero,
        @WebParam(name = "metaMarzo", targetNamespace = "")
        java.lang.Double metaMarzo,
        @WebParam(name = "metaAbril", targetNamespace = "")
        java.lang.Double metaAbril,
        @WebParam(name = "metaMayo", targetNamespace = "")
        java.lang.Double metaMayo,
        @WebParam(name = "metaJunio", targetNamespace = "")
        java.lang.Double metaJunio,
        @WebParam(name = "metaJulio", targetNamespace = "")
        java.lang.Double metaJulio,
        @WebParam(name = "metaAgosto", targetNamespace = "")
        java.lang.Double metaAgosto,
        @WebParam(name = "metaSetiembre", targetNamespace = "")
        java.lang.Double metaSetiembre,
        @WebParam(name = "metaOctubre", targetNamespace = "")
        java.lang.Double metaOctubre,
        @WebParam(name = "metaNoviembre", targetNamespace = "")
        java.lang.Double metaNoviembre,
        @WebParam(name = "metaDiciembre", targetNamespace = "")
        java.lang.Double metaDiciembre
    ) throws WsException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarProyectoCodigoSnip", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyectoCodigoSnip")
    @WebMethod
    @ResponseWrapper(localName = "insertarProyectoCodigoSnipResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProyectoCodigoSnipResponse")
    public java.lang.Short insertarProyectoCodigoSnip(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "codigoSubprograma", targetNamespace = "")
        java.lang.Short codigoSubprograma,
        @WebParam(name = "codigoProyecto", targetNamespace = "")
        java.lang.Short codigoProyecto,
        @WebParam(name = "codigoSnip", targetNamespace = "")
        java.lang.Short codigoSnip
    ) throws WsException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertarPrograma", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarPrograma")
    @WebMethod
    @ResponseWrapper(localName = "insertarProgramaResponse", targetNamespace = "localhost", className = "py.gov.stp.mh.inserts_presupuesto.InsertarProgramaResponse")
    public java.lang.Short insertarPrograma(
        @WebParam(name = "anio", targetNamespace = "")
        java.lang.Short anio,
        @WebParam(name = "nivel", targetNamespace = "")
        java.lang.Short nivel,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.Short entidad,
        @WebParam(name = "tipoPrograma", targetNamespace = "")
        java.lang.Short tipoPrograma,
        @WebParam(name = "codigoPrograma", targetNamespace = "")
        java.lang.Short codigoPrograma,
        @WebParam(name = "nombrePrograma", targetNamespace = "")
        java.lang.String nombrePrograma,
        @WebParam(name = "abrevPrograma", targetNamespace = "")
        java.lang.String abrevPrograma,
        @WebParam(name = "descripcion", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(name = "baseLegal", targetNamespace = "")
        java.lang.String baseLegal,
        @WebParam(name = "resultado", targetNamespace = "")
        java.lang.String resultado,
        @WebParam(name = "codigoDepto", targetNamespace = "")
        java.lang.Short codigoDepto,
        @WebParam(name = "objetivo", targetNamespace = "")
        java.lang.String objetivo,
        @WebParam(name = "diagnostico", targetNamespace = "")
        java.lang.String diagnostico
    ) throws WsException_Exception;
}
