
package py.gov.stp.mh.inserts_presupuesto;

import javax.xml.ws.WebFault;

/**
@author		DGTIC-STP
@email      dgtic@stp.gov.py
*/

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-07-25T08:27:04.982-04:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "WsException", targetNamespace = "http://inserts.service.siaf.hacienda.gov.py/")
public class WsException_Exception extends Exception {
    
    private py.gov.stp.mh.inserts_presupuesto.WsException wsException;

    public WsException_Exception() {
        super();
    }
    
    public WsException_Exception(String message) {
        super(message);
    }
    
    public WsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WsException_Exception(String message, py.gov.stp.mh.inserts_presupuesto.WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WsException_Exception(String message, py.gov.stp.mh.inserts_presupuesto.WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public py.gov.stp.mh.inserts_presupuesto.WsException getFaultInfo() {
        return this.wsException;
    }
}
